name: release 

on:
  pull_request:
    types: [closed]

permissions: 
  contents: write

jobs:
  release:
    if: (github.event.pull_request.merged == true) && (github.repository_owner == 'xianshenglu')
    name: release
    runs-on: ubuntu-latest 

    steps:
      - name: Check out Git repository 
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_BOT_RELEASE  }}
          fetch-depth: 0 # for changeLog

      - name: release
        run: |
          git config --local user.email "xianshenglu@qq.com"
          git config --local user.name "xianshenglu"
          npm i --silent
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
